### Register new user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "Yura",
  "email": "yura@mail.ru",
  "password": "12345678Qw!"
}

### Login user
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "yura@mail.ru",
  "password": "12345678Qw!"
}

> {%
    // В новых версиях HTTP client тело уже разобрано:
    const json = response.body;        // или response.parsedBody

    if (!json || !json.accessToken || !json.refreshToken) {
        console.log("❌ Tokens not found in response:", response.body);
    } else {
        client.global.set("userAccessToken", json.accessToken);
        client.global.set("userRefreshToken", json.refreshToken);

        console.log("✅ Access Token saved:", json.accessToken);
        console.log("✅ Refresh Token saved:", json.refreshToken);
    }
%}





### Create student1
POST http://localhost:8080/api/v1/students
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}

{
  "firstName": "Kuksik",
  "secondName": "Listik",
  "email": "kuksik@mail.ru",
  "birthDate": "1985-02-08"
}

### Create student2
POST http://localhost:8080/api/v1/students
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}

{
  "firstName": "Fedia",
  "secondName": "Funt",
  "email": "fedia@mail.ru",
  "birthDate": "1980-02-08"
}

### Create student3
POST http://localhost:8080/api/v1/students
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}

{
  "firstName": "Oleg",
  "secondName": "Losev",
  "email": "oleg@mail.ru",
  "birthDate": "1990-02-08"
}

### Create student4
POST http://localhost:8080/api/v1/students
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}

{
  "firstName": "John",
  "secondName": "Doe",
  "email": "john.doe@example.com",
  "birthDate": "2000-01-15"
}

### Update token
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
"refreshToken": {{userRefreshToken}}
}

### Обновление студента3 по email
PUT http://localhost:8080/api/v1/students/oleg@mail.ru
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}

{
  "firstName": "Dragon",
  "secondName": "XXX",
  "email": "oleg@mail.ru",
  "birthDate": "1999-01-01"
}

### Удаление студента обычным пользователем (запрет)
DELETE http://localhost:8080/api/v1/students/email/oleg@mail.ru
Authorization: Bearer {{userAccessToken}}




### Login as admin
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@local",
  "password": "admin"
}

> {%
    // В новых версиях HTTP client тело уже разобрано:
    const json = response.body;        // или response.parsedBody

    if (!json || !json.accessToken || !json.refreshToken) {
        console.log("❌ Tokens not found in response:", response.body);
    } else {
        client.global.set("adminAccessToken", json.accessToken);
        client.global.set("adminRefreshToken", json.refreshToken);

        console.log("✅ Access Token saved:", json.accessToken);
        console.log("✅ Refresh Token saved:", json.refreshToken);
    }
%}


### Получение всех студентов
GET http://localhost:8080/api/v1/students
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}

### Удаление студента админом (разрешено)
DELETE http://localhost:8080/api/v1/students/email/oleg@mail.ru
Authorization: Bearer Authorization: Bearer {{adminAccessToken}}

### Генерация 10ти студентов обычным пользователем (запрещено)
POST http://localhost:8080/api/v1/students/generate/10
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{userAccessToken}}

### Генерация 10ти студентов обычным админом (разрешено)
POST http://localhost:8080/api/v1/students/generate/110
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{adminAccessToken}}